databases:
  - name: pdfhub-db
    plan: free
    ipAllowList: []

services:
  - type: web
    name: pdfhub
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /dashboard
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_NAME
        value: PDFHub
      - key: QUEUE_CONNECTION
        value: sync
      - key: MARKER_ENABLED
        value: "false"
      - key: SESSION_DRIVER
        value: file
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: pdfhub-db
          property: connectionString
